version: '2.4'

volumes:
  sense-data:
  grafana-data:

services:
  influxdb:
    image: influxdb:2.7.11
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - sense-data:/var/lib/influxdb2
    environment:
      INFLUXD_LOG_LEVEL: debug
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: "supersecret"
      DOCKER_INFLUXDB_INIT_ORG: balena
      DOCKER_INFLUXDB_INIT_BUCKET: balena-sense
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "mysecrettoken"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
     driver: "json-file"
     options:
      max-size: "10m"
      max-file: "3"
      

  grafana:
    build: ./grafana
    restart: always
    ports:
      - "80:80"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_PORT=80
      - GF_PATHS_PROVISIONING=/usr/src/app/provisioning
      - GF_SESSION_PROVIDER=memory

  counter:
    build: ./counter
    restart: always
    privileged: true
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mysecrettoken
      - INFLUX_ORG=balena
      - INFLUX_BUCKET=balena-sense
