apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    editable: false
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: balena
      defaultBucket: balena-sense
    secureJsonData:
      token: mysecrettoken
